### ISSUE TITLE
To-do list for Tudat (short-term)

### ISSUE THREAD

**Issue by DominicDirkx** [Tudat/tudat#431]
* [x] (M) Update and improve JSON documentation (remaining: tutorial update for remaining two JSON tutorials, using C++; update list of keys)
* [x] (M) Update documentation to C++11 features
* [x] (M) Check if example applications tutorials are entirely up-to-date with code
* [x] (M) Test update to C++11 feature on Mac
* [x] (M) Remove assign::list_of from example applications
* [x] (M) Fix missing elements of Doxygen documentation
* [ ] (M) Update Doxygen server
* [x] (M) Test update to RotationalDynamicsEstimation feature on Mac
* [x] (M) Check whether new implementation of function DirectionBasedForceGuidance::getRotationToGlobalFrame is working correctly; add flexibility to add roll angle.
* [x] (M) Update unperturbed JSON application tutorial to use Earth as global frame origin, and remove Earth ephemeris model.
* [ ] (M) Add doxygen to JSON stuff for estimation

* [x] (D) Add compiler flags to allow compilation of subsets of Tudat (no estimation features; no extended precision)
* [x] (D/M/?) Check install guide on Windows/Mac/Linux

* [x] (D) Write command-line git guide
* [x] (D) Update example applications to C++11 features
* [x] (D) Finalize code in branch https://github.com/DominicDirkx/tudat/tree/RotationalDynamicsEstimation and merge into master. To be done:
    * Remove PodSettings class
    * Add documentation and unit test for initial rotational state (no free mode excitation) determination
* [x] (D) Merge update to C++11 features
* [x] (D) Disable variational equation propagation for propagators with state size 7

* [x] (?) Test update to C++11 feature and RotationalDynamicsEstimation branch on Windows
   * [x] (M) Build variational equations test
   * [x] (D) Correct git commit hash
   * [x] (M) Update Qt screenshot
   * [x] (M) Uninstall/reinstall Qt (mingw 7.3.0 64-bit), and rebuild
   * [x] (M) Check Modified Rodrigues Parameter error
   * [x] (D) Check gravitational torques error
   * [x] (D) Update tudatLinkLibraries.cmake (Estimation libraries)
   * [x] (D) Fix postProcessState compiler warning
   * [x] (D) Add  #include <Eigen/Dense> to torqueModel.h
* [x] (?) Remove assign::list_of from code (lower priority)

* [ ]  (?) Add documentation for VehicleSystems (?)
* [ ]  (?) Valgrind/callgrind documentation

**Comment by mfacchinelli** [comment]
- [ ] Create new JSON interface for RungeKuttaVariableStepSizeSettingsVectorTolerances with extra template
- [ ] Identity elements: fix return size for dynamic matrices and vectors

**Comment by JeffreyNederend** [comment]
- [ ] Add JSON interface to change dependentVariableSaveSetting to true or false

**Comment by DominicDirkx** [comment]
@JeffreyNederend The feature has been added to the code. In case you're interested, teh required changes are shown here:

https://github.com/Tudat/tudat/commit/d30ae4334f6abcbd9a055762fb0429859211650d

As you can, they were quite minimal. The list of keys on the website has also been updated with the new printVariableIndicesToTerminal JSON input option.

Thanks for proposing this, I think it's a very useful feature, at minimal cost :)
